# Generated by Django 4.1.5 on 2025-06-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=12, verbose_name='Tipo')),
                ('business', models.CharField(default='', max_length=12, verbose_name='Negocio')),
                ('model', models.CharField(default='', max_length=12, verbose_name='Modelo')),
                ('orientation', models.CharField(default='', max_length=12, verbose_name='Orientación')),
                ('dimension', models.FloatField(default=0, max_length=12, verbose_name='Metraje útil')),
                ('dimension_total', models.FloatField(default=0, max_length=5, verbose_name='Metraje total')),
                ('status', models.CharField(default='', max_length=5, verbose_name='Estado')),
                ('washing', models.CharField(default='Si', max_length=12, verbose_name='Lavadora')),
                ('floor', models.IntegerField(default=1, max_length=3, verbose_name='Piso')),
            ],
        ),
    ]
