# Generated by Django 4.1.5 on 2025-06-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Piso'),
        ),
    ]
