# Generated by Django 4.1.5 on 2025-06-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vita', '0002_alter_property_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Número'),
        ),
    ]
